language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source;
  - mysql -e "create database IF NOT EXISTS zfc_user;" -uroot

script:
  - ./vendor/bin/phpunit --bootstrap=tests/bootstrap.php
  - ./vendor/bin/phpcs -n --standard=PSR2 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false
  irc: "irc.freenode.org#zftalk.dev"
  
tools:
  external_code_coverage: true

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
